[package]
name = "testing"
version = "0.1.0"
authors = ["David St-Hilaire <sthilaire.david@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.1.40"
rand = "0.8.3"